name: CI

on:
  push:
    branches: ["master"] 
  pull_request:
    branches: ["master"]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      #Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      #Setup node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      #Install dependencies
      - name: Dep Install
        run: npm install

      #Start all nodes
      - name: Start lb + servers
        run: npm run start:all &
      #Give servers time to boot
      - name: Start time
        run: sleep 5

      #Run test
      - name: Run tests
        run: npm test
